// Code generated by entc, DO NOT EDIT.

package device

const (
	// Label holds the string label denoting the device type in the database.
	Label = "device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldSeq holds the string denoting the seq field in the database.
	FieldSeq = "seq"
	// Table holds the table name of the device in the database.
	Table = "device"
)

// Columns holds all SQL columns for device fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldIP,
	FieldModel,
	FieldSeq,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
