// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DeviceColumns holds the columns for the "device" table.
	DeviceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "ip", Type: field.TypeString},
		{Name: "model", Type: field.TypeInt},
		{Name: "seq", Type: field.TypeInt},
	}
	// DeviceTable holds the schema information for the "device" table.
	DeviceTable = &schema.Table{
		Name:        "device",
		Columns:     DeviceColumns,
		PrimaryKey:  []*schema.Column{DeviceColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DeviceTable,
	}
)

func init() {
}
